---
- hosts: 172.31.44.175
  become: yes
  tasks:
  - name: install git
    apt:
     name: git
     state: present
    tags: mygit
  - name: install tree
    apt:
     name: tree
     statee: present
    ignore_errors: yes 
    tags: mytree
  - name: install wget
    apt:
     name: wget
     state: present
    tags: mywget