---
- hosts: 172.31.40.101
  become: yes
  tasks:
  - name: i want install webserver
    apt:
     name: apache2
     state: present
  - name: copy index file into nodes 
    copy:
     src: myindexpage
     dest:  /var/www/html/index.html