---
- name: download tomcat
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz

- name: create tomcat folder
  file:
   path: /opt/tomcat
   state: directory

- name: extract tomcat tar file
  command:
      cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-10*tar.gz -C /opt/tomcat --strip-components=1
      creates: /opt/tomcat/LICENSE
    
    